- name: Install prerequisites
  apt:
    name: ['python3-pip', 'python3-setuptools', 'virtualenv', 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg2' ,'software-properties-common']
    update_cache: yes

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Update repository
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes

- name: run docker and enable on boot
  systemd:
    name: docker
    enabled: yes

- name: Install docker-compose
  pip:
    name: docker-compose
