version: "3.8"
services:
  database:
    container_name: database_pg
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - '5432:5432'
volumes:
  database-data: # named volumes can be managed easier using docker-compose

networks:
  default:
    external:
      name: main