# Generated by Django 3.0.5 on 2020-04-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ursamajor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='page',
            name='download_file',
        ),
        migrations.RemoveField(
            model_name='page',
            name='download_title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='likes',
        ),
    ]
