# Generated by Django 3.0.5 on 2020-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ursamajor', '0002_auto_20200426_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='raw_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
