# Generated by Django 3.0.5 on 2020-04-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ursamajor', '0003_page_raw_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='end_pub_time',
        ),
        migrations.RemoveField(
            model_name='page',
            name='pub_time',
        ),
        migrations.AddField(
            model_name='page',
            name='raw_html',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='translated',
            field=models.BooleanField(blank=True, default='', max_length=255, null=True),
        ),
    ]
