# Generated by Django 3.0.5 on 2020-04-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ursamajor', '0004_auto_20200426_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='add_time',
            new_name='date_create',
        ),
    ]
