# Generated by Django 3.0.5 on 2020-04-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ursamajor', '0005_auto_20200427_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
