# Generated by Django 3.0.5 on 2020-04-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ursamajor', '0007_auto_20200428_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='processed_content',
        ),
    ]
