# Generated by Django 3.0.5 on 2020-05-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ursamajor', '0008_remove_page_processed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='layout',
            field=models.IntegerField(choices=[(0, 'главная'), (1, 'статья'), (2, 'раздел')], null=1, verbose_name='шаблон'),
        ),
    ]
