# Generated by Django 3.0.5 on 2020-05-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ursamajor', '0009_auto_20200503_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='preview',
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='псевдоним'),
        ),
    ]
