version: "3.8"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10M"
    max-file: "10"

services:
  ursamajor_nginx:
    container_name: ursamajor_nginx
    image: gadtakoi/ursamajor:nginx_1.18
    restart: always
    volumes:
      - /opt/ursamajor_static/:/opt/ursamajor_static/
      - ./nginxconfig/nginx.conf:/etc/nginx/nginx.conf
      - ./nginxconfig/sites-enabled/:/etc/nginx/sites-enabled/
      - ./nginxconfig/nginxconfig.io/:/etc/nginx/nginxconfig.io/
      - ./nginxconfig/conf.d/:/etc/nginx/conf.d/
      - /etc/localtime:/etc/localtime:ro
      - /var/log/docker_container/ursamajor_nginx:/var/log/nginx/
    logging: *default-logging
    ports:
      - '80:80'

  ursamajor_app_1:
    image: gadtakoi/ursamajor:app_${VERSION}
    container_name: ursamajor_app_1
    restart: always
    volumes:
      - /opt/ursamajor_static/:/opt/ursamajor_static/
      - ./gunicorn/:/docker/code/gunicorn/
      - /etc/localtime:/etc/localtime:ro
      - /var/log/docker_container/ursamajor_app_1:/var/log
    command: bash -c 'gunicorn -c /docker/code/gunicorn/config.py config.wsgi -p /var/run/gunicorn.pid'
    env_file:
      - ".env"
    logging: *default-logging

  ursamajor_app_2:
    container_name: ursamajor_app_2
    image: gadtakoi/ursamajor:app_${VERSION}
    restart: always
    volumes:
      - /opt/ursamajor_static/:/opt/ursamajor_static/
      - ./gunicorn/:/docker/code/gunicorn/
      - /etc/localtime:/etc/localtime:ro
      - /var/log/docker_container/ursamajor_app_2:/var/log
    command: bash -c 'gunicorn -c /docker/code/gunicorn/config.py config.wsgi -p /var/run/gunicorn.pid'
    env_file:
      - ".env"
    logging: *default-logging

networks:
  default:
    external:
      name: main